name: Test

on:
    push:
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Setup .NET
                uses: actions/setup-dotnet@v2
                with:
                    dotnet-version: 6.x.x
            -   name: Restore dependencies
                run: dotnet restore
            -   name: Build
                run: dotnet build --no-restore
            -   name: Test
                run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
            -   name: Publish coverage report to coveralls.io
                uses: coverallsapp/github-action@master
                with:
                    github-token: ${{ secrets.GITHUB_TOKEN }}
                    path-to-lcov: ./Tests/TestResults/coverage.info

    documentation:
        runs-on: windows-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Setup .NET
                uses: actions/setup-dotnet@v2
                with:
                    dotnet-version: 6.x.x
            -   name: Setup DocFX
                uses: crazy-max/ghaction-chocolatey@v2
                with:
                    args: install docfx
            -   name: DocFX Build
                working-directory: docfx_project
                run: docfx .\docfx.json
                continue-on-error: false
            -   name: Publish
                uses: peaceiris/actions-gh-pages@v3
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    publish_dir: docfx_project/_site
                    force_orphan: true